# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SheetMapImporter
                                 A QGIS plugin
 import map define in a Google Spread Sheet
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-06-17
        copyright            : (C) 2020 by Yoichi Kayama
        email                : yoichi.kayama@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SheetMapImporter class from file SheetMapImporter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SheetMapImporter import SheetMapImporter
    return SheetMapImporter(iface)
